variables:
  CI_REGISTRY_USER: $CI_REGISTRY_USER
  CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CI_REGISTRY: docker.io
  CI_REGISTRY_IMAGE: index.docker.io/tw0flower/matrix-token-webapp

stages:
  - build

services:
  - docker:dind

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build -t matrix-token-webapp:latest .